CREATE SCHEMA todoapp;

CREATE TABLE todoapp.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 1,
    full_name TEXT NOT NULL CHECK (length(trim(full_name)) > 0 AND length(full_name) <= 100),
    phone_number TEXT CHECK (
        phone_number IS NULL OR
        phone_number ~ '^\+[1-9][0-9]{7,14}$'
    )
);


CREATE TABLE todoapp.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 1,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0 AND length(title) <= 100),
    description TEXT CHECK (description IS NULL OR (length(trim(description)) > 0 AND length(description) <= 1000)),
    completed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    author_user_id BIGINT NOT NULL,
    CONSTRAINT tasks_author_user_id_fkey
        FOREIGN KEY (author_user_id) REFERENCES todoapp.users(id),
    CONSTRAINT tasks_completed_at_check
        CHECK (
            (completed = false AND completed_at IS NULL) OR
            (completed = true AND completed_at IS NOT NULL)
        ),
    CONSTRAINT tasks_completed_after_created_check
        CHECK (
            completed_at IS NULL OR
            completed_at >= created_at
        )
);
